In [ ]:
!pip install pingouin
!pip install --upgrade --force-reinstall #link of a private repository
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.decomposition import NMF
from sklearn.feature_extraction.text import TfidfVectorizer
import os

Requirement already satisfied: pingouin in /usr/local/lib/python3.11/dist-packages (0.5.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from pingouin) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from pingouin) (2.2.4)
Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.11/dist-packages (from pingouin) (2.2.3)
Requirement already satisfied: pandas-flavor in /usr/local/lib/python3.11/dist-packages (from pingouin) (0.7.0)
Requirement already satisfied: scikit-learn>=1.2 in /usr/local/lib/python3.11/dist-packages (from pingouin) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from pingouin) (1.14.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (from pingouin) (0.13.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.11/dist-packages (from pingouin) (0.14.4)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from pingouin) (0.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.5->pingouin) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.5->pingouin) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.5->pingouin) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.2->pingouin) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.2->pingouin) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pingouin) (3.2.3)
Requirement already satisfied: xarray in /usr/local/lib/python3.11/dist-packages (from pandas-flavor->pingouin) (2025.1.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels->pingouin) (1.0.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5->pingouin) (1.17.0)
Collecting git+https://github.com/tantantan12/itom6219.git
  Cloning https://github.com/tantantan12/itom6219.git to /tmp/pip-req-build-cqxj469s
  Running command git clone --filter=blob:none --quiet https://github.com/tantantan12/itom6219.git /tmp/pip-req-build-cqxj469s
  Resolved https://github.com/tantantan12/itom6219.git to commit e22b2e16673b5f6f6bf082d4cfe59522517dbbc2
  Preparing metadata (setup.py) ... done
Collecting requests (from itom6219==0.1)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pandas (from itom6219==0.1)
  Using cached pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Collecting numpy>=1.23.2 (from pandas->itom6219==0.1)
  Using cached numpy-2.2.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting python-dateutil>=2.8.2 (from pandas->itom6219==0.1)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas->itom6219==0.1)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas->itom6219==0.1)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting charset-normalizer<4,>=2 (from requests->itom6219==0.1)
  Using cached charset_normalizer-3.4.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (35 kB)
Collecting idna<4,>=2.5 (from requests->itom6219==0.1)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->itom6219==0.1)
  Using cached urllib3-2.4.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->itom6219==0.1)
  Using cached certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->itom6219==0.1)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached certifi-2025.1.31-py3-none-any.whl (166 kB)
Using cached charset_normalizer-3.4.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (143 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached numpy-2.2.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Using cached urllib3-2.4.0-py3-none-any.whl (128 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: itom6219
  Building wheel for itom6219 (setup.py) ... done
  Created wheel for itom6219: filename=itom6219-0.1-py3-none-any.whl size=3751 sha256=ca977d9785f87db37d52adf6abf2dccc73e50d0640f9e15df91e31eee799face
  Stored in directory: /tmp/pip-ephem-wheel-cache-rtrnmf05/wheels/85/b0/8f/0526c1033869bec00e4fcd411eaf1286a58550c082e280ad7d
Successfully built itom6219
Installing collected packages: pytz, urllib3, tzdata, six, numpy, idna, charset-normalizer, certifi, requests, python-dateutil, pandas, itom6219
  Attempting uninstall: pytz
    Found existing installation: pytz 2025.2
    Uninstalling pytz-2025.2:
      Successfully uninstalled pytz-2025.2
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.4.0
    Uninstalling urllib3-2.4.0:
      Successfully uninstalled urllib3-2.4.0
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2025.2
    Uninstalling tzdata-2025.2:
      Successfully uninstalled tzdata-2025.2
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.4
    Uninstalling numpy-2.2.4:
      Successfully uninstalled numpy-2.2.4
  Attempting uninstall: idna
    Found existing installation: idna 3.10
    Uninstalling idna-3.10:
      Successfully uninstalled idna-3.10
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.4.1
    Uninstalling charset-normalizer-3.4.1:
      Successfully uninstalled charset-normalizer-3.4.1
  Attempting uninstall: certifi
    Found existing installation: certifi 2025.1.31
    Uninstalling certifi-2025.1.31:
      Successfully uninstalled certifi-2025.1.31
  Attempting uninstall: requests
    Found existing installation: requests 2.32.3
    Uninstalling requests-2.32.3:
      Successfully uninstalled requests-2.32.3
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.3
    Uninstalling pandas-2.2.3:
      Successfully uninstalled pandas-2.2.3
  Attempting uninstall: itom6219
    Found existing installation: itom6219 0.1
    Uninstalling itom6219-0.1:
      Successfully uninstalled itom6219-0.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.4 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.4 which is incompatible.
Successfully installed certifi-2025.1.31 charset-normalizer-3.4.1 idna-3.10 itom6219-0.1 numpy-2.2.4 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2025.2 requests-2.32.3 six-1.17.0 tzdata-2025.2 urllib3-2.4.0

In [ ]:
import pandas as pd
df=pd.read_csv('food_network.csv')
df.head()

,text,id,created_at,edit_history_tweet_ids,public_metrics.retweet_count,public_metrics.reply_count,public_metrics.like_count,public_metrics.quote_count,public_metrics.bookmark_count,public_metrics.impression_count
0,This two-in-one gadget holds your paper towels...,1777429960132550952,2024-04-08T20:15:00.000Z,['1777429960132550952'],1,1,3,0,1,2615
1,Coming Soon 😎 A new season of #SummerBakingCha...,1777410265639784623,2024-04-08T18:56:44.000Z,"['1777409699387769241', '1777410265639784623']",3,1,33,1,0,9622
2,Introducing: The Lobster Tartine from Fair Hav...,1777399761924149629,2024-04-08T18:15:00.000Z,['1777399761924149629'],2,1,23,0,5,10278
3,"One moment, please 😂\n\nCatch @chefdphillips o...",1777392211664973855,2024-04-08T17:45:00.000Z,['1777392211664973855'],0,2,26,0,0,9667
4,Get ready to dip into a whole new cheesy comfo...,1777384661699948961,2024-04-08T17:15:00.000Z,['1777384661699948961'],6,3,57,1,21,12178

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
docs=df['text']
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.8, min_df=0.02)
tfidf = tfidf_vectorizer.fit_transform(docs)

tfidf_df = pd.DataFrame(tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
tfidf_df

,000,10,10c,11a,24in24,7c,8c,8i77dxphnc,9c,a21schizoidman,...,way,ways,weelicious,whopping,wildcardkitchen,win,winner,work,worthy,year
0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.000000,0.0,0.313388,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.162468,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.269533,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.33549,0.000000,0.0,0.0,0.0,0.0
4,0.0,0.0,0.255891,0.255891,0.0,0.000000,0.000000,0.288605,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.193305,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0
95,0.0,0.0,0.000000,0.000000,0.0,0.305756,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0
96,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.165943,0.000000,0.0,0.0,...,0.264011,0.0,0.234085,0.0,0.20655,0.000000,0.0,0.0,0.0,0.0
97,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0
98,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.315563,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.00000,0.445144,0.0,0.0,0.0,0.0

In [ ]:
# Apply NMF
from sklearn.decomposition import NMF

nmf_model = NMF(n_components=20, random_state=0)
#OpenAI
nmf_model.fit(tfidf)
W= nmf_model.fit_transform(tfidf)  # Document-topic matrix

# Display topics
feature_names = tfidf_vectorizer.get_feature_names_out()
topic_names=[]
for topic_index in range(len(nmf_model.components_)):
    topic = nmf_model.components_[topic_index]
    sorted_indices = topic.argsort()
    top_indices = sorted_indices[-4:]
    top_indices = top_indices[::-1]

    top_words = []
    for i in top_indices:
        top_words.append(feature_names[i])

    top_words_string = " ".join(top_words)

    print("Topic #{}:".format(topic_index))
    print(top_words_string)
    topic_names.append(top_words_string)

topic_df = pd.DataFrame(W, columns=topic_names)
topic_df

Topic #0:
jettila rt chefantonia tonight
Topic #1:
wildcardkitchen aartipaarti gt new
Topic #2:
randomizer a21schizoidman rt going
Topic #3:
day recipe pork best
Topic #4:
maneetchauhan chefantonia break time
Topic #5:
tournamentofchampions think guyfieri trip
Topic #6:
springbakingchampionship 7c nancyfullerco catch
Topic #7:
streamonmax watch ddd guyfieri
Topic #8:
bestbiteintown haven premiere series
Topic #9:
final foodnetwork tournamentofchampions rt
Topic #10:
sunday toc 7c champion
Topic #11:
petit fours advantage tonight
Topic #12:
11a comfort 10c recipes
Topic #13:
don foodnetworkfinds miss need
Topic #14:
make easy links amazon
Topic #15:
battle year chef_rescigno gonna
Topic #16:
glass got ve perfect
Topic #17:
finale live watching rt
Topic #18:
judges omg talk ready
Topic #19:
delicious food dishes ways

,jettila rt chefantonia tonight,wildcardkitchen aartipaarti gt new,randomizer a21schizoidman rt going,day recipe pork best,maneetchauhan chefantonia break time,tournamentofchampions think guyfieri trip,springbakingchampionship 7c nancyfullerco catch,streamonmax watch ddd guyfieri,bestbiteintown haven premiere series,final foodnetwork tournamentofchampions rt,sunday toc 7c champion,petit fours advantage tonight,11a comfort 10c recipes,don foodnetworkfinds miss need,make easy links amazon,battle year chef_rescigno gonna,glass got ve perfect,finale live watching rt,judges omg talk ready,delicious food dishes ways
0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007850,0.433851,0.000000,0.00000,0.000000,0.000000,0.000000
1,0.0,0.009865,0.000000,0.0,0.0,0.000000,0.037662,0.000000,0.012194,0.000000,0.007143,0.155248,0.016026,0.000000,0.000000,0.020871,0.00000,0.110728,0.000000,0.017762
2,0.0,0.000000,0.000000,0.0,0.0,0.001611,0.000000,0.000000,0.569944,0.000000,0.000000,0.000000,0.000000,0.000000,0.011179,0.000000,0.00000,0.000000,0.007807,0.000000
3,0.0,0.136322,0.000000,0.0,0.0,0.000000,0.032186,0.000000,0.018103,0.000000,0.000000,0.000000,0.000000,0.040103,0.000000,0.000000,0.00000,0.000000,0.000000,0.031028
4,0.0,0.002351,0.000000,0.0,0.0,0.000000,0.000000,0.372034,0.000000,0.010833,0.000000,0.000000,0.168643,0.000000,0.000000,0.000000,0.00000,0.000000,0.035970,0.012397
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0.0,0.005842,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.580762,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010676,0.00000,0.000000,0.000000,0.000000
95,0.0,0.000000,0.000000,0.0,0.0,0.095418,0.003871,0.038794,0.000000,0.000000,0.348453,0.000000,0.000000,0.014138,0.000000,0.000000,0.00000,0.136520,0.000000,0.000000
96,0.0,0.116105,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.024992,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.252417,0.000000
97,0.0,0.027476,0.014121,0.0,0.0,0.000000,0.000000,0.000000,0.061354,0.000000,0.000000,0.065892,0.050413,0.000000,0.000000,0.000000,0.02835,0.000000,0.000000,0.010981
98,0.0,0.008820,0.000000,0.0,0.0,0.000000,0.000000,0.025328,0.013661,0.000000,0.000000,0.116540,0.000000,0.000000,0.000000,0.010989,0.00000,0.000000,0.352027,0.000000

In [ ]:
# Code for estimating the linear regression model with the outcome being $log(Likes)$
import pingouin as pg
import numpy as np

# Combine X and y into a single dataframe
# OpenAI
df_model = topic_df.copy()
df_model['like'] =np.log1p(df['public_metrics.like_count']+1)

# Run linear regression
result = pg.linear_regression(df_model.drop(columns='like'), df_model['like'])

# Display R-squared (only need the first row since it's repeated)
r2_1 = round(result['r2'].iloc[0], 3)
print(f"\nR-squared: {r2_1}")

# Round coef and pval to 3 decimal places
result[['names', 'coef', 'pval']] = result[['names', 'coef', 'pval']].round(3)

# Display the rounded result
result[['names', 'coef', 'pval']]

R-squared: 0.567

                                              names    coef   pval
0                                         Intercept   2.984  0.000
1                    jettila rt chefantonia tonight -13.982  0.000
2                wildcardkitchen aartipaarti gt new   8.174  0.081
3                randomizer a21schizoidman rt going  -3.777  0.044
4                              day recipe pork best   0.885  0.750
5              maneetchauhan chefantonia break time   4.497  0.005
6         tournamentofchampions think guyfieri trip   4.557  0.025
7   springbakingchampionship 7c nancyfullerco catch   6.310  0.099
8                    streamonmax watch ddd guyfieri   1.813  0.141
9              bestbiteintown haven premiere series   1.922  0.176
10       final foodnetwork tournamentofchampions rt  -2.784  0.176
11                           sunday toc 7c champion   5.024  0.003
12                    petit fours advantage tonight   1.116  0.594
13                          11a comfort 10c recipes   4.335  0.107
14                   don foodnetworkfinds miss need   2.715  0.164
15                           make easy links amazon   1.091  0.610
16                  battle year chef_rescigno gonna   3.658  0.057
17                             glass got ve perfect   0.405  0.813
18                          finale live watching rt  -1.875  0.222
19                            judges omg talk ready   0.119  0.937
20                       delicious food dishes ways  -0.753  0.546

For Food Network Twitter Topics:
Tweets mentioning "sunday toc 7c champion", "maneetchauhan chefantonia break time", and "tournamentofchampions think guyferi trip" have the most significant positive impact on likes. These topics are associated with high engagement, likely due to their competitive or personality-driven nature.
Meanwhile, "jettila rt chefantonia tonight" and "final foodnetwork tournamentofchampions rt" are significantly negatively associated with likes, suggesting possible overuse or saturation in those topics.

AI Application Twitter Strategy：

- Just like "sunday toc 7c champion", competition signals excellence and drives curiosity. So we can post weekly posts showcasing how AI outperforms traditional tools (e.g., "Our AI completed this task 3x faster than human benchmarks")